name:                linear-instances
version:             0.1.0.0
github:              "fabricatedmath/linear-instances"
license:             BSD3
author:              "Charles Durham"
maintainer:          "fabricatedmath@gmail.com"
copyright:           "2018 Charles Durham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fabricatedmath/linear-instances#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- linear

library:
  source-dirs: src
